const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const PoblacionalMatriculado = sequelize.define('poblacional_matriculados', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  anio: { type: DataTypes.INTEGER, allowNull: false },
  codigo_ies: { type: DataTypes.STRING(20), allowNull: true },
  nombre_ies: { type: DataTypes.STRING(220), allowNull: true },
  semestre: { type: DataTypes.STRING(20), allowNull: true },
  participante: { type: DataTypes.STRING(120), allowNull: true },
  tipo_documento: { type: DataTypes.STRING(40), allowNull: true },
  numero_documento: { type: DataTypes.STRING(80), allowNull: true },
  otros_documentos: { type: DataTypes.STRING(220), allowNull: true },
  codigo_estudiante: { type: DataTypes.STRING(80), allowNull: true },
  sexo_biologico: { type: DataTypes.STRING(40), allowNull: true },
  primer_nombre: { type: DataTypes.STRING(120), allowNull: true },
  segundo_nombre: { type: DataTypes.STRING(120), allowNull: true },
  primer_apellido: { type: DataTypes.STRING(120), allowNull: true },
  segundo_apellido: { type: DataTypes.STRING(120), allowNull: true },
  programa_consecutivo: { type: DataTypes.STRING(80), allowNull: true },
  programa: { type: DataTypes.STRING(260), allowNull: true },
  codigo_dane: { type: DataTypes.STRING(5), allowNull: true },
  codigo_departamento: { type: DataTypes.STRING(2), allowNull: true },
  departamento: { type: DataTypes.STRING(140), allowNull: true },
  municipio: { type: DataTypes.STRING(180), allowNull: true },
  fecha_nacimiento: { type: DataTypes.STRING(80), allowNull: true },
  id_pais: { type: DataTypes.STRING(20), allowNull: true },
  pais: { type: DataTypes.STRING(140), allowNull: true },
  codigo_dane_nacimiento: { type: DataTypes.STRING(5), allowNull: true },
  codigo_departamento_nacimiento: { type: DataTypes.STRING(2), allowNull: true },
  departamento_nacimiento: { type: DataTypes.STRING(140), allowNull: true },
  municipio_nacimiento: { type: DataTypes.STRING(180), allowNull: true },
  id_zona_residencia: { type: DataTypes.STRING(20), allowNull: true },
  zona_residencia: { type: DataTypes.STRING(120), allowNull: true },
  numero_materias_inscritas: { type: DataTypes.INTEGER, allowNull: true },
  numero_materias_aprobadas: { type: DataTypes.INTEGER, allowNull: true },
  es_reintegro_estd_antes_de1998: { type: DataTypes.STRING(10), allowNull: true },
  anio_primer_curso: { type: DataTypes.INTEGER, allowNull: true },
  semestre_primer_curso: { type: DataTypes.STRING(20), allowNull: true },
  valor_derechos_matricula: { type: DataTypes.DECIMAL(14, 2), allowNull: true },
  estrato: { type: DataTypes.STRING(20), allowNull: true },
  fuente: { type: DataTypes.STRING(120), allowNull: true },
  fecha_ultimo_cargue: { type: DataTypes.STRING(40), allowNull: true },
  match_confianza_ubicacion: { type: DataTypes.STRING(20), allowNull: true },
  match_metodo_ubicacion: { type: DataTypes.STRING(40), allowNull: true },
  match_score_ubicacion: { type: DataTypes.DECIMAL(6, 3), allowNull: true },
  match_actualizado_en: { type: DataTypes.DATE, allowNull: true },
  creado_por: { type: DataTypes.INTEGER, allowNull: true },
  actualizado_por: { type: DataTypes.INTEGER, allowNull: true }
});

module.exports = PoblacionalMatriculado;
