import api from './api';

const root = '/strategic-planning';
const data = (response) => response.data;

const strategicPlanningService = {
  bootstrap: () => api.get(`${root}/bootstrap`).then(data),
  listPlans: () => api.get(`${root}/plans`).then(data),
  createPlan: (payload) => api.post(`${root}/plans`, payload).then(data),
  updatePlan: (id, payload) => api.patch(`${root}/plans/${id}`, payload).then(data),
  deletePlan: (id) => api.delete(`${root}/plans/${id}`).then(data),
  createLevel: (planId, payload) => api.post(`${root}/plans/${planId}/levels`, payload).then(data),
  updateLevel: (planId, levelId, payload) => api.patch(`${root}/plans/${planId}/levels/${levelId}`, payload).then(data),
  deleteLevel: (planId, levelId) => api.delete(`${root}/plans/${planId}/levels/${levelId}`).then(data),
  listStructure: (planId) => api.get(`${root}/plans/${planId}/structure`).then(data),
  createElement: (planId, payload) => api.post(`${root}/plans/${planId}/elements`, payload).then(data),
  updateElement: (planId, elementId, payload) => api.patch(`${root}/plans/${planId}/elements/${elementId}`, payload).then(data),
  deleteElement: (planId, elementId) => api.delete(`${root}/plans/${planId}/elements/${elementId}`).then(data),
  applyInstitutionalTemplate: (planId) => api.post(`${root}/plans/${planId}/apply-institutional-template`).then(data),
  createField: (planId, payload) => api.post(`${root}/plans/${planId}/fields`, payload).then(data),
  updateField: (planId, fieldId, payload) => api.patch(`${root}/plans/${planId}/fields/${fieldId}`, payload).then(data),
  deleteField: (planId, fieldId) => api.delete(`${root}/plans/${planId}/fields/${fieldId}`).then(data),
  upsertCatalog: (planId, payload) => api.post(`${root}/plans/${planId}/catalog-items`, payload).then(data),
  updateCatalog: (planId, itemId, payload) => api.patch(`${root}/plans/${planId}/catalog-items/${itemId}`, payload).then(data),
  deleteCatalog: (planId, itemId) => api.delete(`${root}/plans/${planId}/catalog-items/${itemId}`).then(data),
  previewReferences: (planId, formData) => api.post(`${root}/plans/${planId}/reference-imports/preview`, formData, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 60000 }).then(data),
  confirmReferences: (importId) => api.post(`${root}/reference-imports/${importId}/confirm`).then(data),
  leaderOptions: (planId) => api.get(`${root}/plans/${planId}/leader-options`).then(data),
  createTerm: (planId, payload) => api.post(`${root}/plans/${planId}/terms`, payload).then(data),
  updateTerm: (termId, payload) => api.patch(`${root}/terms/${termId}`, payload).then(data),
  deleteTerm: (termId) => api.delete(`${root}/terms/${termId}`).then(data),
  listActionPlans: (params = {}) => api.get(`${root}/action-plans`, { params }).then(data),
  getActionPlan: (id) => api.get(`${root}/action-plans/${id}`).then(data),
  exportActionPlan: (id) => api.get(`${root}/action-plans/${id}/export`, { responseType: 'blob', timeout: 60000 }).then((response) => response.data),
  createActionPlan: (payload) => api.post(`${root}/action-plans`, payload).then(data),
  updateActionPlan: (id, payload) => api.patch(`${root}/action-plans/${id}`, payload).then(data),
  addItem: (id, payload) => api.post(`${root}/action-plans/${id}/items`, payload).then(data),
  updateItem: (id, itemId, payload) => api.patch(`${root}/action-plans/${id}/items/${itemId}`, payload).then(data),
  transition: (id, payload) => api.post(`${root}/action-plans/${id}/transitions`, payload).then(data),
  transferLeader: (id, payload) => api.post(`${root}/action-plans/${id}/transfer-leader`, payload).then(data),
  saveMonitoring: (itemId, periodId, payload) => api.put(`${root}/action-items/${itemId}/monitoring/${periodId}`, payload).then(data),
  createMeeting: (id, payload) => api.post(`${root}/action-plans/${id}/meetings`, payload).then(data),
  createMinute: (meetingId, payload = {}) => api.post(`${root}/meetings/${meetingId}/minutes`, payload).then(data),
  publishMinute: (minuteId) => api.post(`${root}/minutes/${minuteId}/publish`).then(data),
  finalizeMinute: (minuteId, payload = {}) => api.post(`${root}/minutes/${minuteId}/finalize`, payload).then(data),
  uploadEvidence: (itemId, formData) => api.post(`${root}/action-items/${itemId}/evidence`, formData, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 60000 }).then(data),
  reconcile: (termId) => api.post(`${root}/terms/${termId}/reconcile`).then(data),
  closeTerm: (termId) => api.post(`${root}/terms/${termId}/close`).then(data),
  syncJobs: () => api.get(`${root}/sync-jobs`).then(data),
  analytics: (params = {}) => api.get(`${root}/analytics`, { params }).then(data),
  audit: () => api.get(`${root}/audit`).then(data),
  previewBudget: (formData) => api.post(`${root}/budget-imports/preview`, formData, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 60000 }).then(data),
  confirmBudget: (id) => api.post(`${root}/budget-imports/${id}/confirm`).then(data),
  previewHistorical: (formData) => api.post(`${root}/historical-imports/preview`, formData, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 60000 }).then(data),
  publicMinute: (token) => api.get(`/public/strategic-planning/minutes/${token}`, { skipAuthRedirect: true }).then(data),
  requestCode: (token, payload) => api.post(`/public/strategic-planning/minutes/${token}/request-code`, payload, { skipAuthRedirect: true }).then(data),
  signExternal: (token, payload) => api.post(`/public/strategic-planning/minutes/${token}/sign`, payload, { skipAuthRedirect: true }).then(data)
};

export default strategicPlanningService;
